# check=skip=InvalidBaseImagePlatform
################################################################################
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

ARG MANYLINUX_IMAGE=quay.io/pypa/manylinux2014_x86_64
FROM ${MANYLINUX_IMAGE}

ARG JDK8_URL=https://api.adoptium.net/v3/binary/latest/8/ga/linux/x64/jdk/hotspot/normal/eclipse
ARG MAVEN_VERSION=3.9.9
ARG SPARK_VERSION=3.4.4
ARG SPARK_TGZ_URL=https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop3.tgz
ARG SPARK_LOCAL_KIND=none
ARG INSTALL_SPARK=0
ARG RUST_TOOLCHAIN=stable

ENV JAVA_HOME=/opt/java/openjdk
ENV MAVEN_HOME=/opt/maven
ENV SPARK_HOME=/opt/spark
ENV CARGO_HOME=/usr/local/cargo
ENV RUSTUP_HOME=/usr/local/rustup
ENV PATH=${MAVEN_HOME}/bin:${CARGO_HOME}/bin:${SPARK_HOME}/bin:${JAVA_HOME}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN set -eux; \
    mkdir -p "${JAVA_HOME}"; \
    curl -fsSL "${JDK8_URL}" -o /tmp/jdk8.tar.gz; \
    tar -xzf /tmp/jdk8.tar.gz -C "${JAVA_HOME}" --strip-components=1; \
    rm -f /tmp/jdk8.tar.gz

RUN set -eux; \
    mkdir -p "${MAVEN_HOME}"; \
    curl -fsSL "https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz" -o /tmp/maven.tgz; \
    tar -xzf /tmp/maven.tgz -C "${MAVEN_HOME}" --strip-components=1; \
    rm -f /tmp/maven.tgz

COPY spark-local /tmp/spark-local

RUN set -eux; \
    case "${INSTALL_SPARK}" in \
      1|true|TRUE|yes|YES|y|Y) \
        case "${SPARK_LOCAL_KIND}" in \
          tgz) \
            tar -xzf /tmp/spark-local/spark.tgz -C /opt; \
            mv "/opt/spark-${SPARK_VERSION}-bin-hadoop3" "${SPARK_HOME}"; \
            ;; \
          dir) \
            mkdir -p "${SPARK_HOME}"; \
            cp -a /tmp/spark-local/spark/. "${SPARK_HOME}/"; \
            ;; \
          none) \
            curl -fsSL "${SPARK_TGZ_URL}" -o /tmp/spark.tgz; \
            tar -xzf /tmp/spark.tgz -C /opt; \
            mv "/opt/spark-${SPARK_VERSION}-bin-hadoop3" "${SPARK_HOME}"; \
            rm -f /tmp/spark.tgz; \
            ;; \
          *) \
            echo "Unsupported SPARK_LOCAL_KIND: ${SPARK_LOCAL_KIND}" >&2; \
            exit 1; \
            ;; \
        esac; \
        ;; \
      *) \
        echo "Skipping Spark binary installation for jar packaging image."; \
        ;; \
    esac

RUN set -eux; \
    curl -fsSL https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain "${RUST_TOOLCHAIN}"; \
    chmod -R a+rX "${CARGO_HOME}" "${RUSTUP_HOME}"

RUN set -eux; \
    ldd --version | sed -n '1p'; \
    java -version; \
    mvn -version; \
    rustc --version; \
    cargo --version; \
    if [ -x "${SPARK_HOME}/bin/spark-submit" ]; then spark-submit --version; fi

WORKDIR /work/nativeio/paimon
